# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_department_staff_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department_Staff',
            new_name='ListOfStaff',
        ),
    ]
