# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20180622_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofstaff',
            name='profile_picture',
        ),
    ]
