# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-05 20:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.IntegerField(default=0)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Exco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(blank=True, choices=[(b'', b''), (b'President', b'President'), (b'Vice President', b'Vice President'), (b'Secretery General', b'Secretery General'), (b'Ass. Secretery General', b'Ass. Secretery General'), (b'Auditor General', b'Auditor General'), (b'Welfare Director', b'Welfare Director'), (b'Financial Sec.', b'Financial Sec.')], max_length=50, null=True)),
                ('from_date', models.DateField(auto_now_add=True)),
                ('to_date', models.DateField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_of_residence', models.CharField(blank=True, choices=[(b'OFF CAMPUS', b'OFF CAMPUS'), (b'KABIRU UMAR', b'KABIRU UMAR'), (b'USMAN NAGOGGO', b'USMAN NAGOGGO'), (b'NANA ASMAU', b'NANA ASMAU'), (b'OBA ADETOLA', b'OBA ADETOLA'), (b'NEW HOSTEL - MALE', b'NEW HOSTEL - MALE'), (b'NEW HOSTEL - FEMALE', b'NEW HOSTEL - FEMALE')], max_length=50, null=True)),
                ('state_of_origin', models.CharField(blank=True, choices=[(b'Abia', b'Abia'), (b'Adamawa', b'Adamawa')], max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Office')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aspirant',
            name='aspiring_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Office'),
        ),
    ]
