# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_d_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_exco',
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[(b'President', b'President'), (b'Vice President', b'Vice President'), (b'Secretery General', b'Secretery General'), (b'Ass. Secretery General', b'Ass. Secretery General'), (b'Auditor General', b'Auditor General'), (b'Welfare Director', b'Welfare Director'), (b'Financial Sec.', b'Financial Sec.')], default=b'Member', max_length=50),
        ),
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(blank=True, choices=[(b'Abia', b'Abia'), (b'Adamawa', b'Adamawa')], max_length=50, null=True),
        ),
    ]
