# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20180414_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hall_of_residence',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
