# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ID_Number',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Student ID number'),
            preserve_default=False,
        ),
    ]
