# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20180621_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exco',
            name='office',
            field=models.CharField(blank=True, choices=[(b'', b''), (b'President', b'President'), (b'Vice President', b'Vice President'), (b'Secretery General', b'Secretery General'), (b'Ass. Secretery General', b'Ass. Secretery General'), (b'Auditor General', b'Auditor General'), (b'Welfare Director', b'Welfare Director'), (b'Financial Sec.', b'Financial Sec.')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[(b'', b''), (b'President', b'President'), (b'Vice President', b'Vice President'), (b'Secretery General', b'Secretery General'), (b'Ass. Secretery General', b'Ass. Secretery General'), (b'Auditor General', b'Auditor General'), (b'Welfare Director', b'Welfare Director'), (b'Financial Sec.', b'Financial Sec.')], default=b'Member', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state_of_origin',
            field=models.CharField(blank=True, choices=[(b'Abia', b'Abia'), (b'Adamawa', b'Adamawa')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
