# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180621_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_exco',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a exco', verbose_name='is exco'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[(b'', b''), (b'President', b'President'), (b'Vice President', b'Vice President'), (b'Secretery General', b'Secretery General'), (b'Ass. Secretery General', b'Ass. Secretery General'), (b'Auditor General', b'Auditor General'), (b'Welfare Director', b'Welfare Director'), (b'Financial Sec.', b'Financial Sec.')], default=b'Member', help_text='Leave blank for regular student', max_length=50, null=True),
        ),
    ]
