# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20180417_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectionSession',
        ),
    ]
