# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20180622_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[(b'100', b'100'), (b'200', b'200'), (b'300', b'300'), (b'400', b'400'), (b'500', b'500'), (b'Graduated', b'Graduated')], default=100, max_length=9),
        ),
    ]
