# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text=b'499 x 499 pixels recommnded', null=True, upload_to=b'profile_pictures'),
        ),
    ]
