# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-11 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import voting.models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20180509_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default=b'368', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default=b'269', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default=b'no_image/default_user_image.png', height_field=b'image_height', help_text=b'499 x 499 pixels recommnded', null=True, upload_to=voting.models.path_and_rename, width_field=b'image_width'),
        ),
    ]
