# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-05 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180705_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hall_of_residence',
            field=models.CharField(blank=True, choices=[(b'OFF CAMPUS', b'OFF CAMPUS'), (b'KABIRU UMAR', b'KABIRU UMAR'), (b'USMAN NAGOGGO', b'USMAN NAGOGGO'), (b'NANA ASMAU', b'NANA ASMAU'), (b'OBA ADETOLA', b'OBA ADETOLA'), (b'NEW HOSTEL - MALE', b'NEW HOSTEL - MALE'), (b'NEW HOSTEL - FEMALE', b'NEW HOSTEL - FEMALE')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state_of_origin',
            field=models.CharField(blank=True, choices=[(b'Abia', b'Abia'), (b'Adamawa', b'Adamawa')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
