# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-05 22:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_of_residence', models.CharField(blank=True, choices=[(b'OFF CAMPUS', b'OFF CAMPUS'), (b'KABIRU UMAR', b'KABIRU UMAR'), (b'USMAN NAGOGGO', b'USMAN NAGOGGO'), (b'NANA ASMAU', b'NANA ASMAU'), (b'OBA ADETOLA', b'OBA ADETOLA'), (b'NEW HOSTEL - MALE', b'NEW HOSTEL - MALE'), (b'NEW HOSTEL - FEMALE', b'NEW HOSTEL - FEMALE')], max_length=50, null=True)),
                ('state_of_origin', models.CharField(blank=True, choices=[(b'Abia', b'Abia'), (b'Adamawa', b'Adamawa')], max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_updated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
